// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _28_WebAPI_Example;

#nullable disable

namespace _28_WebAPI_Example.Migrations
{
    [DbContext(typeof(ExampleDbContext))]
    partial class ExampleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("_28_WebAPI_Example.Models.Rechnung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ergebnis")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Zahl1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Zahl2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("op")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rechnungen");
                });
#pragma warning restore 612, 618
        }
    }
}
